trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: gitversion/setup@0
  displayName: Install GitVersion
  inputs:
    versionSpec: '5.x'
    configFilePath: GitVersion.yml
- task: gitversion/execute@0
  displayName: Determine Version
  inputs:
    useConfigFile: true
- bash: dotnet restore VpNet.sln
  displayName: Restore packages
- bash: dotnet build VpNet.sln -c $(buildConfiguration) --no-restore -p:Version=$(GitVersion.NuGetVersion)
  displayName: Build solution
- bash: dotnet pack VpNet/VpNet.csproj --no-build --output $(Build.ArtifactStagingDirectory)/packages -p:Version=$(GitVersion.NuGetVersion)
  displayName: Pack
- publish: $(Build.ArtifactStagingDirectory)/packages
  artifact: packages
