using System;

namespace VpNet.NativeApi
{
    internal enum IntegerAttribute
    {
        AvatarSession,
        AvatarType,
        MyType,
        ObjectId,
        ObjectType,
        ObjectTime,
        ObjectUserId,
        WorldState,
        WorldUsers,
        ReferenceNumber,
        CurrentCallback,
        UserId,
        UserRegistrationTime,
        UserOnlineTime,
        UserLastLogin,
        [Obsolete] FriendId,
        [Obsolete] FriendUserId,
        [Obsolete] FriendOnline,
        MyUserId,
        ProxyType,
        ProxyPort,
        CellX,
        CellZ,
        TerrainTileX,
        TerrainTileZ,
        TerrainNodeX,
        TerrainNodeZ,
        TerrainNodeRevision,
        ClickedSession,
        ChatType,
        ChatColorRed,
        ChatColorGreen,
        ChatColorBlue,
        ChatEffects,
        DisconnectErrorCode,
        UrlTarget,
        CurrentEvent,
        CellRevision = 38,
        CellStatus,
        JoinId,
        InviteId,
        InviteUserId
    }
}
