namespace VpNet.NativeApi
{
    internal enum StringAttribute
    {
        AvatarName,
        ChatMessage,
        ObjectModel,
        ObjectAction,
        ObjectDescription,
        WorldName,
        UserName,
        UserEmail,
        WorldSettingKey,
        WorldSettingValue,
        FriendName,
        ProxyHost,
        TeleportWorld,
        Url,
        JoinWorld,
        JoinName,
        StartWorld,
        InviteName,
        InviteWorld,
        ApplicationName,
        ApplicationVersion,
        AvatarApplicationName,
        AvatarApplicationVersion
    }
}
