using System;

namespace VpNet
{
    /// <summary>
    ///     Represents the method that will handle a VP event when the event provides data.
    /// </summary>
    /// <typeparam name="T">The type of the event data generated by the event.</typeparam>
    /// <param name="sender">The source of the event.</param>
    /// <param name="args">An object that contains the event data.</param>
    public delegate void VpEventHandler<in T>(VirtualParadiseClient sender, T args) where T : EventArgs;
}
